### ISSUE TITLE
Is there an options for this to return a JS date object? 

### ISSUE THREAD

**Issue by insivika** [wojtekmaj/react-timerange-picker#10]
I see the string value being return which in itself is not very useful for subsequent interaction. Is there anyway I can return the javascript date object as well?

**Comment by wojtekmaj** [comment]
Hi,
since in "time range" there's no such thing as "date", we can't return a specific `Date` object. Due to timezones and DST, there's no date we could auto-pick to keep everyone happy. 

What you can do is use React-DateTimeRange-Picker and disable date picking, or simply transform the time into a date object with a date of your choice. Shouldn't be too hard!

```js
// assuming time = '20:41:52';
const date = new Date(2019, 0, 1, ...time.split(':'));
```
