### ISSUE TITLE
If there is an event that can be called when minutes are written more then 59 ?

### ISSUE THREAD

**Issue by Asuddle** [wojtekmaj/react-timerange-picker#28]
If there is an event that can be called when minutes are written more then 59 . When I write date more then 59 , it show the error but it take the first digit as input for eg if i write 64 . it will take 6 as input and show error and doesn;t add input 4 . if it can handled through an event?

**Comment by wojtekmaj** [comment]
Native date/time pickers never send onChange with invalid values, that's why React-TimeRange-Picker also does not.

However, you have a couple of events that might help you because they are happily bubbling:
* onInput
* onInvalid

First one would allow you to check the input for invalid values by doing [`input.checkValidity()`](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation), the second will fire if you try to submit an invalid value.
